src/Entity/Role.php
<?php

namespace App\Entity;

use App\Repository\RoleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RoleRepository::class)]
class Role
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $libelle = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $code_role = null;

    #[ORM\OneToMany(mappedBy: 'role', targetEntity: Menu::class)]
    private Collection $menus;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(?string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getCodeRole(): ?string
    {
        return $this->code_role;
    }

    public function setCodeRole(?string $code_role): self
    {
        $this->code_role = $code_role;

        return $this;
    }
    public function __toString(){
        return $this->libelle;
    }

    /**
     * @return Collection<int, Menu>
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus->add($menu);
            $menu->setRole($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->removeElement($menu)) {
            // set the owning side to null (unless already changed)
            if ($menu->getRole() === $this) {
                $menu->setRole(null);
            }
        }

        return $this;
    }

}

src/Form/RoleType.php
<?php

namespace App\Form;

use App\Entity\Role;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code_role',TextType::class,[
            'label'=>'Rang :' ,
            'label_attr'=>['class'=>"m-5"],
            'attr'=>['class'=>'m-3']
            ])
            ->add('libelle',TextType::class,[
                'label'=>'Libellé :',
                'label_attr'=>['class'=> "m-5"]
            ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Role::class,
        ]);
    }
}

src/Controller/RoleController.php
<?php

namespace App\Controller;

use App\Entity\Role;
use App\Form\RoleType;
use App\Repository\RoleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/role')]
class RoleController extends AbstractController
{
    #[Route('/', name: 'app_role_index', methods: ['GET'])]
    public function index(RoleRepository $roleRepository): Response
    {
        return $this->render('role/index.html.twig', [
            'roles' => $roleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_role_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RoleRepository $roleRepository): Response
    {
        $role = new Role();
        $form = $this->createForm(RoleType::class, $role);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $roleRepository->save($role, true);

            return $this->redirectToRoute('app_role_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('role/new.html.twig', [
            'role' => $role,
            'form' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'app_role_show', methods: ['GET'])]
    public function show(Role $role): Response
    {
        return $this->render('role/show.html.twig', [
            'role' => $role,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_role_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Role $role, RoleRepository $roleRepository): Response
    {
        $form = $this->createForm(RoleType::class, $role);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $roleRepository->save($role, true);

            return $this->redirectToRoute('app_role_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('role/edit.html.twig', [
            'role' => $role,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_role_delete', methods: ['POST','GET'])]
    public function delete(Request $request, Role $role, RoleRepository $roleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$role->getId(), $request->request->get('_token'))) {
            $roleRepository->remove($role, true);
        }

        return $this->redirectToRoute('app_role_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/role/_delete_form.html.twig
<form method="post" action="{{ path('app_role_delete', {'id': role.id}) }}" onsubmit="return confirm('Etes-vous sûre de vouloir supprimer ce rôle ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ role.id) }}">
    <button class="btn btn-md btn-red">Supprimer</button>
</form>

templates/role/_form.html.twig
{{ form_start(form) }}

    <div class="m-auto w-50 border border-1 border-color shadow bg-clear py-3 px-5">
        <div class="row g-2">
            {{ form_label(form.code_role,'Code :',{'label_attr':{'class':'mt-4'}}) }}
            {{ form_widget(form.code_role,{'attr':{'class':'form-control'}} )}}
        </div>
        <div class="row g-2">
            {{ form_label(form.libelle,'Libellé :',{'label_attr':{'class':'mt-4'}}) }}
            {{ form_widget(form.libelle,{'attr':{'class':'form-control'}} )}}
        </div>
        <div class="d-flex align-items-center justify-content-end m-5">
            <button class="btn bg-green text-clear">
                {{ button_label|default('Valider') }}
            </button>
        </div>
    </div>

{{ form_end(form) }}

templates/role/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateur/ Modifier le Rôle{% endblock %}

{% block body %}

    {# titre #}
	<div class="container p-5 mt-5 bg-blueclear">
		<h1 class="pt-2 pb-5 text-clear">Modifier le rôle</h1>
	</div>

	{# Bouton retour #}
	<div class="container d-md-flex p-5 justify-content-md-start">
		<button class="btn bg-blue mx-5 align-start">
			<a class="text-clear" href="javascript:history.back()">Retour</a>
		</button>
	</div>

	{# formulaire #}
	<div class="container w-50 mb-5">
		{{ include('role/_form.html.twig') }}
	</div>
   
{% endblock %}

templates/role/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateur/liste des Rôles{% endblock %}

{% block body %}

{# titre #}
<div class="container p-5 my-5 bg-blueclear">
  <h1 class="pt-2 pb-5 text-clear">Liste des rôles</h1>
</div>

{# boutons #}
<div class="container d-flex justify-content-between py-5 d-print-none">
  <button class="btn bg-blue">
    <a class="text-clear" href="{{ path('app_role_new') }}">Nouveau rôle</a>
  </button>
 <button class="btn bg-green">
    <a class="btn bg-green text-clear" type="button" onclick="print_page()">Imprimer</a>
 </button>
</div>

{# table #}
<div class="d-flex justify-content-center mb-5">
  <table class="table table responsive w-75">
    <thead class="bg-blue text-clear">
      <tr>
        <th>Id</th>
        <th>Rang</th>
        <th>Libelle</th>
        <th class="text-center d-print-none">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for role in roles %}
      <tr>
        <td>{{ role.id }}</td>
        <td>{{ role.codeRole }}</td>
        <td>{{ role.libelle }}</td>
        <td class="d-flex justify-content-center d-print-none">
          <button class="btn bg-blue mx-3"><a class="text-clear" href="{{ path('app_role_edit', {'id': role.id}) }}">Modifier</a></button>
         {{ include('role/_delete_form.html.twig') }}
        </td>
      </tr>
      {% else %}
      <tr>
        <td colspan="9">Aucune donnée trouvée</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/role/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateur/ Nouveau Rôle{% endblock %}

{% block body %}

{# titre #}
<div class="container p-5 my-5 bg-blueclear">
  <h1 class="pt-2 pb-5 text-clear">Créer un nouveau rôle</h1>
</div>

{# Bouton retour #}
<div class="container">
    <button class="btn bg-blue"><a class="text-clear" href="javascript:history.back()">Retour</a></button>
</div>

{# Formulaire #}
<div class="container mb-5">
    {{ include('role/_form.html.twig') }}
</div>

{% endblock %}

templates/role/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateur/rôle{% endblock %}

{% block body %}
    <div class="bg-blueclear p-5 mb-5">
        <h1>Liste des Rôles</h1>
    </div>
    <div class="m-auto w-50 border border-1 border-color shadow bg-clear">
        <table class="table table-responsive">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ role.id }}</td>
                </tr>
                <tr>
                    <th>Rang</th>
                    <td>{{ role.codeRole }}</td>
                </tr>
                <tr>
                    <th>Libellé</th>
                    <td>{{ role.libelle }}</td>
                </tr>
            </tbody>
    
        </table>
     </div>
     <div class="d-flex justify-content-around m-5">
    <a class="btn btn-md btn-blue" href="{{ path('app_role_index') }}">Revenir à la liste</a>

    <a class="btn btn-md btn-green" href="{{ path('app_role_edit', {'id': role.id}) }}">Modifier</a>

    {{ include('role/_delete_form.html.twig') }}
    </div>
{% endblock %}