src/Entity/GroupeCursus.php
<?php

namespace App\Entity;

use App\Repository\GroupeCursusRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GroupeCursusRepository::class)]
class GroupeCursus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $codeGpeCursus = null;

    #[ORM\Column(length: 30)]
    private ?string $libelleGpeCursus = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToOne]
    private ?Cursus $Cursus = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeGpeCursus(): ?string
    {
        return $this->codeGpeCursus;
    }

    public function setCodeGpeCursus(string $codeGpeCursus): self
    {
        $this->codeGpeCursus = $codeGpeCursus;

        return $this;
    }

    public function getLibelleGpeCursus(): ?string
    {
        return $this->libelleGpeCursus;
    }

    public function setLibelleGpeCursus(string $libelleGpeCursus): self
    {
        $this->libelleGpeCursus = $libelleGpeCursus;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getCursus(): ?Cursus
    {
        return $this->Cursus;
    }

    public function setCursus(?Cursus $Cursus): self
    {
        $this->Cursus = $Cursus;

        return $this;
    }

    public function __toString()
    {
        // $libelle = $this->libelleGpeCursus;
        // $dateDebut = $this->dateDebut;
        // $dateFin = $this->dateFin;
        // return "$libelle | du $dateDebut au $dateFin";
        return $this->libelleGpeCursus;
    }
}

src/Entity/PreInscription.php
<?php

namespace App\Entity;

use App\Repository\PreInscriptionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PreInscriptionRepository::class)]
class PreInscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $sexe = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(nullable: true)]
    private ?int $codePostal = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $region = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $pays = null;
   
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $motivations = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $financement = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carteIdentite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carteIdentiteNom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $justifFinancement = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $justifFinancementNom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carteVitale = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carteVitaleNom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $autreDoc = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $autreDocNom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $n_ss = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $telephone = null;

    #[ORM\ManyToOne(inversedBy: 'preInscriptions')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(?int $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMotivations(): ?string
    {
        return $this->motivations;
    }

    public function setMotivations(?string $motivations): self
    {
        $this->motivations = $motivations;

        return $this;
    }

    public function getFinancement(): ?string
    {
        return $this->financement;
    }

    public function setFinancement(?string $financement): self
    {
        $this->financement = $financement;

        return $this;
    }

    public function getCarteIdentite(): ?string
    {
        return $this->carteIdentite;
    }

    public function setCarteIdentite(?string $carteIdentite): self
    {
        $this->carteIdentite = $carteIdentite;

        return $this;
    }

    public function getCarteIdentiteNom(): ?string
    {
        return $this->carteIdentite;
    }

    public function setCarteIdentiteNom(?string $carteIdentiteNom): self
    {
        $this->carteIdentiteNom = $carteIdentiteNom;

        return $this;
    }

    public function getJustifFinancement(): ?string
    {
        return $this->justifFinancement;
    }

    public function setJustifFinancement(?string $justifFinancement): self
    {
        $this->justifFinancement = $justifFinancement;

        return $this;
    }

    public function getJustifFinancementNom(): ?string
    {
        return $this->justifFinancementNom;
    }

    public function setJustifFinancementNom(?string $justifFinancementNom): self
    {
        $this->justifFinancementNom = $justifFinancementNom;

        return $this;
    }

    public function getCarteVitale(): ?string
    {
        return $this->carteVitale;
    }

    public function setCarteVitale(?string $carteVitale): self
    {
        $this->carteVitale = $carteVitale;

        return $this;
    }

    public function getCarteVitaleNom(): ?string
    {
        return $this->carteVitaleNom;
    }

    public function setCarteVitaleNom(?string $carteVitaleNom): self
    {
        $this->carteVitaleNom = $carteVitaleNom;

        return $this;
    }

    public function getAutreDoc(): ?string
    {
        return $this->autreDoc;
    }

    public function setAutreDoc(?string $autreDoc): self
    {
        $this->autreDoc = $autreDoc;

        return $this;
    }

    public function getAutreDocNom(): ?string
    {
        return $this->autreDocNom;
    }

    public function setAutreDocNom(?string $autreDocNom): self
    {
        $this->autreDocNom = $autreDocNom;

        return $this;
    }

    public function getNSs(): ?string
    {
        return $this->n_ss;
    }

    public function setNSs(?string $n_ss): self
    {
        $this->n_ss = $n_ss;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }  

    public function __toString(){
        return $this->id;
        return $this->carteIdentite;
        return $this->justifFinancement;
        return $this->carteVitale;
        return $this->autreDoc;
    }
    
}

src/Controller/PdfController.php
<?php

namespace App\Controller;

use App\Entity\InscriptionApprenant;
use App\Entity\PreInscription;
use Doctrine\ORM\EntityManagerInterface;
use Spipu\Html2Pdf\Html2Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pdf')]
class PdfController extends AbstractController
{
    // fonction qui liste les pdf disponibles
    #[Route('/', name: 'app_pdf')]
    public function index(): Response
    {
        return $this->render('pdf/index.html.twig');
    }

    // fonction qui génère le pdf du tableau des inscrits
    #[Route('/inscription', name: 'app_inscription_pdf', methods: ['GET'])]
    public function pdfListInscrit(EntityManagerInterface $em)
    {
        $inscriptions = $em->getRepository(InscriptionApprenant::class)->findAll();
        $html = $this->renderView('pdf/inscription_liste_pdf.html.twig', [
            'inscriptions' => $inscriptions
        ]);
        $html2pdf = new Html2Pdf('L', 'A4', 'fr');
        $fichier = 'liste_inscrits.pdf';
        $html2pdf->writeHTML($html);
        $html2pdf->output($fichier, 'D');
    }

    // fonction qui génère le pdf du dossier inscrit
    #[Route('/inscription/{id}', name: 'app_inscription_apprenant_pdf', methods: ['GET'])]
    public function pdfInscrit(EntityManagerInterface $em, $id)
    {
       $inscription = $em->getRepository(InscriptionApprenant::class)->find($id);

       $html = $this->renderView('pdf/inscription_apprenant_pdf.html.twig', [
        'inscription_apprenant' => $inscription
       ]);
       $html2pdf = new Html2Pdf('P', 'A4', 'fr');
       $fichier = 'inscription_apprenant.pdf';
       $html2pdf->writeHTML($html);
       $html2pdf->output($fichier, 'D');
    }

     // fonction qui génère le pdf du dossier de pré-inscription
     #[Route('/pre_inscription/{id}', name: 'app_pre_inscription_apprenant_pdf', methods: ['GET'])]
     public function pdfPreInscrit(EntityManagerInterface $em, $id)
     {
        $pre_inscription = $em->getRepository(PreInscription::class)->find($id);
 
        $html = $this->renderView('pdf/pre_inscription_pdf.html.twig', [
         'pre_inscription' => $pre_inscription
        ]);
        $html2pdf = new Html2Pdf('P', 'A4', 'fr');
        $fichier = 'pre_inscription.pdf';
        $html2pdf->writeHTML($html);
        $html2pdf->output($fichier, 'D');
     }

    // fonction qui génère le pdf du formulaire de préinscription
    #[Route('/preinscription', name: 'app_preinscription_pdf')]
    public function pdfPreinscription() {

        $html = $this->renderView('pdf/preinscription_form.html.twig');
        $html2pdf = new Html2Pdf('P', 'A4');
        $fichier = 'formulaire_inscription.pdf';
        $html2pdf->writeHTML($html);
        $html2pdf->output($fichier, 'D');
    }

}

templates/pdf/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liens de téléchargement{% endblock %}

{% block body %}
{# titre #}
<div class="container p-5 mt-5 bg-blueclear">
  <h1 class="pt-2 pb-5 text-clear">Liens de téléchargement</h1>
</div>

{# Bouton retour #}
<div class="container p-5 d-md-flex justify-content-md-start">
  <button class="btn bg-blue align-start">
    <a class="text-clear" href="javascript:history.back()">Retour</a>
  </button>
</div>

{# liste des liens #}
<div class="d-md-flex justify-content-evenly m-5">
    <button class="btn bg-green"><a class="text-clear" href="">Liste des pré-inscriptions</a></button>
    <button class="btn bg-green"><a class="text-clear" href="{{ path('app_inscription_pdf')}}">Liste des inscriptions</a></button>
    <button class="btn bg-green"><a class="text-clear" href="">Liste des utilisateurs</a></button>
</div>

{% endblock %}

templates/pdf/inscription_apprenant_pdf.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inscription</title>
    <style>
      .title {
        background-color: #3c8cd7;
        padding: 20px;
        margin: 20px;
      }
      h1 {
        margin-bottom: 40px;
        color: #f9f5f6;
        font-size: larger;
      }
      .content {
        padding: 20px;
        margin-left: 80px;
      }
      p{
        padding: 0px;
        margin: 2px;
      }
      .flex {
        display: flex;
      }
    </style>
  </head>
  <body>
    <div class="title">
      <h1>Inscription</h1>
    </div>
    <div class="content">
      <h3>Récapitulatif du dossier</h3>
      <div class="flex">
        <p><b>Id :</b> {{ inscription_apprenant.id }}</p>
        <p><b>Nom :</b> {{ inscription_apprenant.nom }}</p>
        <p><b>Prénom :</b> {{ inscription_apprenant.prenom }}</p>
        <p><b>Identifiant :</b> {{ inscription_apprenant.identifiant }}</p>
        <p><b>E-mail :</b> {{ inscription_apprenant.email }}</p>
        <p><b>Téléphone :</b> {{ inscription_apprenant.telephone }}</p>
        <p>
          <b>N° de sécurité sociale :</b> {{ inscription_apprenant.numSecu }}
        </p>
        <p>
          <b>Date de naissance :</b>
          {{ inscription_apprenant.dateNaissance ? inscription_apprenant.dateNaissance|date('d/m/Y') : '' }}
        </p>
        <p><b>Sexe :</b> {{ inscription_apprenant.sexe }}</p>
        <p><br /></p>
        <p><b>Adresse :</b> {{ inscription_apprenant.adresse }}</p>
        <p><b>Code postal :</b> {{ inscription_apprenant.codePostal }}</p>
        <p><b>Ville :</b> {{ inscription_apprenant.ville }}</p>
        <p><b>Région :</b> {{ inscription_apprenant.region }}</p>
        <p><b>Pays :</b> {{ inscription_apprenant.pays }}</p>
        <p>
          <b>Date d'inscription :</b>
          {{ inscription_apprenant.dateInscription ? inscription_apprenant.dateInscription|date('d/m/Y') : '' }}
        </p>
        <p><b>Cursus :</b> {{ inscription_apprenant.cursus }}</p>
        {# trouver un moyen d'afficher les dates aussi #}
        <p><b>Groupe :</b> {{ inscription_apprenant.groupeCursus }}</p>
        <p><b>Formation :</b> {{ inscription_apprenant.parcours }}</p>
        <p><br /></p>
        <p><b>Financement :</b> {{ inscription_apprenant.financement }}</p>
        <p>
          <b>Mode de paiement :</b> {{ inscription_apprenant.modePaiement }}
        </p>
        <p><b>Montant :</b> {{ inscription_apprenant.montant }}€</p>
        <p>
          <b>Nombre d'échéances :</b> {{ inscription_apprenant.nbEcheance }}
        </p>
      </div>
    </div>
  </body>
</html>

templates/pdf/inscription_liste_pdf.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Projet Apprenant | Inscriptions</title>
    <style>
        .title{background-color: #3c8cd7; padding: 20px; margin: 20px;}
        h1{margin-bottom: 40px; color: #f9f5f6; font-size: larger;}
        .content{padding: 20px; margin-left: 80px;}
        table{}
        th, td{font-size: large;}
        .header{background-color: #153c51;}
        th{color: #f9f5f6; padding: 10px 30px; text-align: center;}
        td{padding: 15px 0; padding-left: 10px;}
    </style>
  </head>
  <body>
    <div class="title">
      <h1>Liste des inscriptions</h1>
    </div>
    <div class="content">
        <table>
          <thead>
            <tr class="header">
              <th>Identifiant</th>
              <th>Nom</th>
              <th>Prénom</th>
              <th>Date de naissance</th>
              <th>Téléphone</th>
              <th>Adresse e-mail</th>
            </tr>
          </thead>
          <tbody>
            {% for inscription_apprenant in inscriptions %}
            <tr>
              <td>{{ inscription_apprenant.identifiant }}</td>
              <td>{{ inscription_apprenant.nom }}</td>
              <td>{{ inscription_apprenant.prenom }}</td>
              <td>
                {{ inscription_apprenant.dateNaissance ? inscription_apprenant.dateNaissance|date('d/m/Y') : '' }}
              </td>
              <td>{{ inscription_apprenant.telephone }}</td>
              <td>{{ inscription_apprenant.email }}</td>
            </tr>
            {% else %}
            <tr>
              <td colspan="6">Aucune donnée trouvée</td>
            </tr>
            {% endfor %}
          </tbody>
          <tfoot>
            <tr class="header">
                <th colspan="6">Projet Apprenant | 2023</th>
            </tr>
          </tfoot>
        </table>
      </div>
  </body>
</html>

templates/pdf/pre_inscription_pdf.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Inscription</title>
        <style>
            .title {
                background-color: #3c8cd7;
                padding: 20px;
                margin: 20px;
            }
            h1 {
                margin-bottom: 40px;
                color: #f9f5f6;
                font-size: larger;
            }
            .content {
                padding: 20px;
                margin-left: 80px;
            }
            p{
                padding: 0px;
                margin: 2px;
            }
            .flex {
                display: flex;
            }
        </style>
    </head>
    <body>
        <div class="title">
            <h1>Inscription</h1>
        </div>
        <div class="content">
            <h3>Récapitulatif du dossier</h3>
            <div class="flex">
                <p><b>Nom :</b> {{ pre_inscription.nom }}</p>
                <p><b>Prénom :</b> {{ pre_inscription.prenom }}</p>
                <p><b>Date de naissance :</b> {{  pre_inscription.dateNaissance ? pre_inscription.dateNaissance|date('Y-m-d') : '' }}</p>
                <p><b>E-mail :</b> {{ pre_inscription.email }}</p>
                <p><b>Téléphone :</b> {{ pre_inscription.telephone }}</p>
                <p><b>N° de sécurité sociale :</b> {{ pre_inscription.nSs }}</p>
                <p><b>Sexe :</b> {{ pre_inscription.sexe }}</p>
                <p><b>Adresse :</b> {{ pre_inscription.adresse }}</p>
                <p><b>Code postal :</b> {{ pre_inscription.codePostal }}</p>
                <p><b>Ville :</b> {{ pre_inscription.ville }}</p>
                <p><b>Région :</b> {{ pre_inscription.region }}</p>
                <p><b>Pays :</b> {{ pre_inscription.pays }}</p>
                <p><b>Carte d'identité :</b> {{ pre_inscription.carteIdentite }}</p>
                <p><b>Justificatif de financement :</b> {{ pre_inscription.justifFinancement }}</p>
                <p><b>Carte vitale :</b> {{ pre_inscription.carteVitale }}</p>
                <p><b>Autre document :</b> {{ pre_inscription.autreDoc }}</p>
                <p><b>Motivations :</b> <br> {{ pre_inscription.motivations }}</p>
                <p><b>Financement :</b> <br> {{ pre_inscription.financement }}</p>
            </div>
        </div>
    </body>
</html>

templates/pdf/preinscription_form.html.twig
<style type="text/css">
  table.page_header {
    width: 100%;
    border: none;
    background-color: #f9f5f6;
    border-bottom: solid 1mm #3c8cd7;
    padding: 2mm;
  }
  table.page_footer {
    width: 100%;
    border: none;
    background-color: #f9f5f6;
    border-top: solid 1mm #3c8cd7;
    padding: 2mm;
  }
  div.note {
    border: solid 1mm #dddddd;
    background-color: #f9f5f6;
    padding: 2mm;
    border-radius: 2mm;
    width: 100%;
  }
  ul.main {
    width: 95%;
    list-style-type: square;
  }
  ul.main li {
    padding-bottom: 2mm;
  }
  h1 {
    text-align: center;
    font-size: 10mm;
  }
  h3 {
    text-align: center;
    font-size: 14mm;
  }
  .input{
    background-color: #f9f5f6;
    border: #3c8cd7 solid 1px;
    height: 20px;
  }
  .input2{
    background-color: #f9f5f6;
    border: #3c8cd7 solid 1px;
    height: 200px;
  }
  .ligne {
    margin-top: 10px;
  }
  td {
    text-align: end;
  }
</style>
<page
  backtop="14mm"
  backbottom="14mm"
  backleft="10mm"
  backright="10mm"
  style="font-size: 12pt"
>
<page_header>
    <table class="page_header">
      <tr>
        <td style="width: 100%; text-align: center">
          Projet Apprenant | Formulaire d'inscription
        </td>
      </tr>
    </table>
</page_header>
<page_footer>
    <table class="page_footer">
      <tr>
        <td style="width: 100%; text-align: center">Afpa 2023</td>
      </tr>
    </table>
  </page_footer>
  <h1>Formulaire d'inscription</h1>
  <br><br><br>
  <h2>Informations personnelles</h2>
  <br>
  <table style="width: 70%">
    <tr>
        <td>Nom : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Prénom : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Date de naissance : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Téléphone : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>E-mail : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Num de Sécurité sociale : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Adresse : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Code postal : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Ville : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Région : </td>
        <td><div class="input"></div><br></td>
    </tr>
    <tr>
        <td>Pays : </td>
        <td><div class="input"></div><br></td>
    </tr>
  </table>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <h2>Inscription au cursus</h2>
  <br>
  <table style="width: 70%">
    <tr>
        <td>Expliquez en quelques phrases vos motivations<br>
        <i>(1000 caractères maximum)</i></td>
    </tr>
    <tr>
        <td><div class="input2"></div><br></td>
    </tr>
    <tr>
        <td>Quels parcours et quel type de financement souhaitez-vous ?<br>
        <i>(500 caractères maximum)</i></td>
    </tr>
    <tr>
        <td><div class="input2"></div><br></td>
    </tr>
  </table>
  <h2>Pièces justificatives</h2>
  <table style="width: 70%">
    <tr>
        <td>
            <h4>Liste des pièces à fournir afin de compléter votre dossier</h4>
        </td><br>
    </tr>
    <tr>
        <td><input type="checkbox">  Catre d'identité<br><br></td>
    </tr>
    <tr>
        <td><input type="checkbox">  Justificatif de financement<br><br></td>
    </tr>
    <tr>
        <td><input type="checkbox">  Attestation de carte Vitale<br><br></td>
    </tr>
    <tr>
        <td>
            <i>Vous pouvez joindre des documents de votre choix pour compléter votre inscription</i><br>
            <input type="checkbox">  Autre document<br>
       </td>
    </tr>
  </table>
</page>